module.exports = {
    address :require('./address'),
    admin_defaults :require('./admin_defaults'),
    admin :require('./admin'),
    app_versions :require('./app_versions'),
    cart :require('./cart'),
    category:require('./category'),
    coupan :require('./coupan'),
    detailed_sub_category : require('./detailed_sub_category'),
    notification :require('./notification'),
    order :require('./order'),
    product_inventary :require('./product_inventary'),
    product :require('./product'),
    refund :require('./refund'),
    state_tax :require('./state_tax'),
    sub_category:require('./sub_category'),
    tag :require('./tag'),
    transaction :require('./transaction'),
    user:require('./user'),
};
